// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Zhua.Infrastructure.Persistence;

#nullable disable

namespace Zhua.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ZhuaDbContext))]
    [Migration("20260627024936_CanonicalProductDescription")]
    partial class CanonicalProductDescription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProductTagStoreProduct", b =>
                {
                    b.Property<Guid>("ProductsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("uuid");

                    b.HasKey("ProductsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("ProductTagStoreProduct");
                });

            modelBuilder.Entity("StoreCategoryStoreProduct", b =>
                {
                    b.Property<Guid>("CategoriesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductsId")
                        .HasColumnType("uuid");

                    b.HasKey("CategoriesId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("StoreCategoryStoreProduct");
                });

            modelBuilder.Entity("Zhua.Domain.Entities.CanonicalCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("CanonicalCategories");
                });

            modelBuilder.Entity("Zhua.Domain.Entities.CanonicalProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid?>("CanonicalCategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Gtin")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("MatchKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Size")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UnitOfMeasure")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalCategoryId");

                    b.HasIndex("Category");

                    b.HasIndex("Gtin");

                    b.HasIndex("MatchKey")
                        .IsUnique()
                        .HasFilter("\"MatchKey\" IS NOT NULL");

                    b.ToTable("CanonicalProducts");
                });

            modelBuilder.Entity("Zhua.Domain.Entities.CrawlRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProductsFound")
                        .HasColumnType("integer");

                    b.Property<int>("SnapshotsWritten")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StoreId", "StartedAt");

                    b.ToTable("CrawlRuns");
                });

            modelBuilder.Entity("Zhua.Domain.Entities.MatchCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CanonicalProductId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("StoreProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalProductId");

                    b.HasIndex("Status");

                    b.HasIndex("StoreProductId", "CanonicalProductId")
                        .IsUnique();

                    b.ToTable("MatchCandidates");
                });

            modelBuilder.Entity("Zhua.Domain.Entities.PriceSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CrawlRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<bool>("IsOnSpecial")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("NonSpecialPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("StoreProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.HasKey("Id");

                    b.HasIndex("CrawlRunId");

                    b.HasIndex("StoreProductId", "CapturedAt");

                    b.ToTable("PriceSnapshots");
                });

            modelBuilder.Entity("Zhua.Domain.Entities.ProductTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Chain")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Chain", "Source", "Code")
                        .IsUnique();

                    b.ToTable("ProductTags");
                });

            modelBuilder.Entity("Zhua.Domain.Entities.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Chain")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ExternalStoreId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Suburb")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Chain");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Chain = "Woolworths",
                            IsActive = true,
                            Latitude = -36.7879,
                            Longitude = 174.76949999999999,
                            Name = "Woolworths Takapuna",
                            Suburb = "Takapuna"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            Chain = "Woolworths",
                            IsActive = false,
                            Latitude = -36.780700000000003,
                            Longitude = 174.72280000000001,
                            Name = "Woolworths Glenfield",
                            Suburb = "Glenfield"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111113"),
                            Chain = "Woolworths",
                            IsActive = false,
                            Latitude = -36.7166,
                            Longitude = 174.7466,
                            Name = "Woolworths Browns Bay",
                            Suburb = "Browns Bay"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Chain = "NewWorld",
                            ExternalStoreId = "60928d93-06fa-4d8f-92a6-8c359e7e846d",
                            IsActive = true,
                            Latitude = -36.846400000000003,
                            Longitude = 174.76589999999999,
                            Name = "New World Metro Auckland",
                            Suburb = "Auckland Central"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222223"),
                            Chain = "NewWorld",
                            ExternalStoreId = "1898a189-acf3-4320-8704-7a9cc6b3924d",
                            IsActive = true,
                            Latitude = -36.787599999999998,
                            Longitude = 174.77000000000001,
                            Name = "New World Shore City",
                            Suburb = "Takapuna"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222224"),
                            Chain = "NewWorld",
                            ExternalStoreId = "dbdfdd2a-55f7-4870-9b51-979286323647",
                            IsActive = true,
                            Latitude = -36.716000000000001,
                            Longitude = 174.7473,
                            Name = "New World Browns Bay",
                            Suburb = "Browns Bay"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Chain = "PaknSave",
                            ExternalStoreId = "65defcf2-bc15-490e-a84f-1f13b769cd22",
                            IsActive = true,
                            Latitude = -36.729999999999997,
                            Longitude = 174.70670000000001,
                            Name = "PAK'nSAVE Albany",
                            Suburb = "Albany"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333334"),
                            Chain = "PaknSave",
                            ExternalStoreId = "60561e46-ece7-43a7-b142-9b14812586e4",
                            IsActive = true,
                            Latitude = -36.930700000000002,
                            Longitude = 174.91300000000001,
                            Name = "PAK'nSAVE Botany",
                            Suburb = "Botany"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333335"),
                            Chain = "PaknSave",
                            ExternalStoreId = "2a1b331a-fc4a-496a-b072-e97cc8f70cae",
                            IsActive = true,
                            Latitude = -36.898899999999998,
                            Longitude = 174.90469999999999,
                            Name = "PAK'nSAVE Highland Park",
                            Suburb = "Highland Park"
                        });
                });

            modelBuilder.Entity("Zhua.Domain.Entities.StoreCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CanonicalCategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalCategoryId");

                    b.HasIndex("ParentId");

                    b.HasIndex("StoreId", "Kind", "ExternalId")
                        .IsUnique();

                    b.ToTable("StoreCategories");
                });

            modelBuilder.Entity("Zhua.Domain.Entities.StoreProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CanonicalProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("CurrentNonSpecialPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("CurrentPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Gtin")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsOnSpecial")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("PriceUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RawBrand")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("RawName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("RawSize")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SourceSku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid");

                    b.Property<string>("UnitOfMeasure")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<string>("Url")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalProductId");

                    b.HasIndex("Gtin");

                    b.HasIndex("StoreId", "SourceSku")
                        .IsUnique();

                    b.ToTable("StoreProducts");
                });

            modelBuilder.Entity("ProductTagStoreProduct", b =>
                {
                    b.HasOne("Zhua.Domain.Entities.StoreProduct", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zhua.Domain.Entities.ProductTag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StoreCategoryStoreProduct", b =>
                {
                    b.HasOne("Zhua.Domain.Entities.StoreCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zhua.Domain.Entities.StoreProduct", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Zhua.Domain.Entities.CanonicalCategory", b =>
                {
                    b.HasOne("Zhua.Domain.Entities.CanonicalCategory", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Zhua.Domain.Entities.CanonicalProduct", b =>
                {
                    b.HasOne("Zhua.Domain.Entities.CanonicalCategory", "CanonicalCategory")
                        .WithMany("Products")
                        .HasForeignKey("CanonicalCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CanonicalCategory");
                });

            modelBuilder.Entity("Zhua.Domain.Entities.CrawlRun", b =>
                {
                    b.HasOne("Zhua.Domain.Entities.Store", "Store")
                        .WithMany("CrawlRuns")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Zhua.Domain.Entities.MatchCandidate", b =>
                {
                    b.HasOne("Zhua.Domain.Entities.CanonicalProduct", "CanonicalProduct")
                        .WithMany()
                        .HasForeignKey("CanonicalProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zhua.Domain.Entities.StoreProduct", "StoreProduct")
                        .WithMany()
                        .HasForeignKey("StoreProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CanonicalProduct");

                    b.Navigation("StoreProduct");
                });

            modelBuilder.Entity("Zhua.Domain.Entities.PriceSnapshot", b =>
                {
                    b.HasOne("Zhua.Domain.Entities.CrawlRun", "CrawlRun")
                        .WithMany("PriceSnapshots")
                        .HasForeignKey("CrawlRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zhua.Domain.Entities.StoreProduct", "StoreProduct")
                        .WithMany("PriceSnapshots")
                        .HasForeignKey("StoreProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CrawlRun");

                    b.Navigation("StoreProduct");
                });

            modelBuilder.Entity("Zhua.Domain.Entities.StoreCategory", b =>
                {
                    b.HasOne("Zhua.Domain.Entities.CanonicalCategory", "CanonicalCategory")
                        .WithMany("StoreCategories")
                        .HasForeignKey("CanonicalCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Zhua.Domain.Entities.StoreCategory", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Zhua.Domain.Entities.Store", "Store")
                        .WithMany("StoreCategories")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CanonicalCategory");

                    b.Navigation("Parent");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Zhua.Domain.Entities.StoreProduct", b =>
                {
                    b.HasOne("Zhua.Domain.Entities.CanonicalProduct", "CanonicalProduct")
                        .WithMany("StoreProducts")
                        .HasForeignKey("CanonicalProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Zhua.Domain.Entities.Store", "Store")
                        .WithMany("StoreProducts")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CanonicalProduct");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Zhua.Domain.Entities.CanonicalCategory", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Products");

                    b.Navigation("StoreCategories");
                });

            modelBuilder.Entity("Zhua.Domain.Entities.CanonicalProduct", b =>
                {
                    b.Navigation("StoreProducts");
                });

            modelBuilder.Entity("Zhua.Domain.Entities.CrawlRun", b =>
                {
                    b.Navigation("PriceSnapshots");
                });

            modelBuilder.Entity("Zhua.Domain.Entities.Store", b =>
                {
                    b.Navigation("CrawlRuns");

                    b.Navigation("StoreCategories");

                    b.Navigation("StoreProducts");
                });

            modelBuilder.Entity("Zhua.Domain.Entities.StoreCategory", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Zhua.Domain.Entities.StoreProduct", b =>
                {
                    b.Navigation("PriceSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
