// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Zhua.Infrastructure.Persistence;

#nullable disable

namespace Zhua.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ZhuaDbContext))]
    [Migration("20260620122133_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Zhua.Domain.Entities.CanonicalProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Gtin")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Size")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UnitOfMeasure")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Gtin");

                    b.ToTable("CanonicalProducts");
                });

            modelBuilder.Entity("Zhua.Domain.Entities.CrawlRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProductsFound")
                        .HasColumnType("integer");

                    b.Property<int>("SnapshotsWritten")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StoreId", "StartedAt");

                    b.ToTable("CrawlRuns");
                });

            modelBuilder.Entity("Zhua.Domain.Entities.PriceSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CrawlRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<bool>("IsOnSpecial")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("NonSpecialPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("StoreProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.HasKey("Id");

                    b.HasIndex("CrawlRunId");

                    b.HasIndex("StoreProductId", "CapturedAt");

                    b.ToTable("PriceSnapshots");
                });

            modelBuilder.Entity("Zhua.Domain.Entities.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Chain")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ExternalStoreId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Suburb")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Chain");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Chain = "Woolworths",
                            IsActive = true,
                            Latitude = -36.7879,
                            Longitude = 174.76949999999999,
                            Name = "Woolworths Takapuna",
                            Suburb = "Takapuna"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Chain = "NewWorld",
                            IsActive = true,
                            Latitude = -36.786799999999999,
                            Longitude = 174.7731,
                            Name = "New World Takapuna",
                            Suburb = "Takapuna"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Chain = "PaknSave",
                            IsActive = true,
                            Latitude = -36.778300000000002,
                            Longitude = 174.74469999999999,
                            Name = "PAK'nSAVE Glenfield",
                            Suburb = "Glenfield"
                        });
                });

            modelBuilder.Entity("Zhua.Domain.Entities.StoreProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CanonicalProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("CurrentPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("CurrentSpecial")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Gtin")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsOnSpecial")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("PriceUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RawBrand")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("RawName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("RawSize")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SourceSku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid");

                    b.Property<string>("UnitOfMeasure")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<string>("Url")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalProductId");

                    b.HasIndex("Gtin");

                    b.HasIndex("StoreId", "SourceSku")
                        .IsUnique();

                    b.ToTable("StoreProducts");
                });

            modelBuilder.Entity("Zhua.Domain.Entities.CrawlRun", b =>
                {
                    b.HasOne("Zhua.Domain.Entities.Store", "Store")
                        .WithMany("CrawlRuns")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Zhua.Domain.Entities.PriceSnapshot", b =>
                {
                    b.HasOne("Zhua.Domain.Entities.CrawlRun", "CrawlRun")
                        .WithMany("PriceSnapshots")
                        .HasForeignKey("CrawlRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zhua.Domain.Entities.StoreProduct", "StoreProduct")
                        .WithMany("PriceSnapshots")
                        .HasForeignKey("StoreProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CrawlRun");

                    b.Navigation("StoreProduct");
                });

            modelBuilder.Entity("Zhua.Domain.Entities.StoreProduct", b =>
                {
                    b.HasOne("Zhua.Domain.Entities.CanonicalProduct", "CanonicalProduct")
                        .WithMany("StoreProducts")
                        .HasForeignKey("CanonicalProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Zhua.Domain.Entities.Store", "Store")
                        .WithMany("StoreProducts")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CanonicalProduct");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Zhua.Domain.Entities.CanonicalProduct", b =>
                {
                    b.Navigation("StoreProducts");
                });

            modelBuilder.Entity("Zhua.Domain.Entities.CrawlRun", b =>
                {
                    b.Navigation("PriceSnapshots");
                });

            modelBuilder.Entity("Zhua.Domain.Entities.Store", b =>
                {
                    b.Navigation("CrawlRuns");

                    b.Navigation("StoreProducts");
                });

            modelBuilder.Entity("Zhua.Domain.Entities.StoreProduct", b =>
                {
                    b.Navigation("PriceSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
